# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import changing_dot.generated_grpc.feedback_server_pb2 as feedback__server__pb2


class FeedbackServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCompileErrors = channel.unary_unary(
            "/feedback_server.FeedbackServer/GetCompileErrors",
            request_serializer=feedback__server__pb2.GetCompileErrorsRequest.SerializeToString,
            response_deserializer=feedback__server__pb2.GetCompileErrorsReply.FromString,
        )
        self.HasSyntaxErrors = channel.unary_unary(
            "/feedback_server.FeedbackServer/HasSyntaxErrors",
            request_serializer=feedback__server__pb2.HasSyntaxErrorsRequest.SerializeToString,
            response_deserializer=feedback__server__pb2.HasSyntaxErrorsReply.FromString,
        )


class FeedbackServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCompileErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HasSyntaxErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FeedbackServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetCompileErrors": grpc.unary_unary_rpc_method_handler(
            servicer.GetCompileErrors,
            request_deserializer=feedback__server__pb2.GetCompileErrorsRequest.FromString,
            response_serializer=feedback__server__pb2.GetCompileErrorsReply.SerializeToString,
        ),
        "HasSyntaxErrors": grpc.unary_unary_rpc_method_handler(
            servicer.HasSyntaxErrors,
            request_deserializer=feedback__server__pb2.HasSyntaxErrorsRequest.FromString,
            response_serializer=feedback__server__pb2.HasSyntaxErrorsReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "feedback_server.FeedbackServer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class FeedbackServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCompileErrors(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/feedback_server.FeedbackServer/GetCompileErrors",
            feedback__server__pb2.GetCompileErrorsRequest.SerializeToString,
            feedback__server__pb2.GetCompileErrorsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def HasSyntaxErrors(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/feedback_server.FeedbackServer/HasSyntaxErrors",
            feedback__server__pb2.HasSyntaxErrorsRequest.SerializeToString,
            feedback__server__pb2.HasSyntaxErrorsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
